############################################
# Video
############################################

profile=gpu-hq
vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe

# Better scaling
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

# Debanding
deband=yes

# Interpolation (smooth playback)
video-sync=display-resample
interpolation=yes
tscale=oversample

############################################
# Audio
############################################

volume=100
audio-display=no

############################################
# Window
############################################

keep-open=yes
save-position-on-quit=yes
force-window=yes
autofit-larger=90%x90%

############################################
# Subtitles
############################################

sub-auto=fuzzy
slang=en

sub-font="JetBrainsMono Nerd Font"
sub-font-size=46
sub-border-size=2
sub-shadow-offset=0
sub-scale-with-window=yes

############################################
# Screenshots
############################################

screenshot-format=png
screenshot-png-compression=6
screenshot-directory=~/Pictures/Screenshots

############################################
# OSD
############################################

osc=yes
osd-bar=yes
osd-font-size=32
osd-duration=2000

############################################
# Misc
############################################

watch-later-options=start
prefetch-playlist=yes
resume-playback=yes

save-position-on-quit=yes

cursor-autohide=1000

# Better seeking
hr-seek=yes

############################################
# Cache
############################################

cache=yes
demuxer-max-bytes=512MiB
demuxer-max-back-bytes=128MiB
