config_version = 2

[audio]
enable_overdrive = true

[backdrop]
blur_intensity = 0.24999999441206455
enabled = true

[bar.default]
background_opacity = 0.59999998658895493
center = [ "date", "spacer_2", "clock" ]
end = [ "media", "tray", "notifications", "battery", "control-center" ]
margin_ends = 0
position = "left"
radius = 0
radius_bottom_right = 10
radius_top_right = 10
start = [ "launcher", "workspaces", "active_window" ]
thickness = 28

[control_center]
hidden_tabs = [ "monitor", "power", "screen-time" ]
width = 600

    [control_center.calendar]
    show_events_card = false

[dock]
auto_hide = true
background_opacity = 0.59999998658895493
cross_axis_padding = 5
enabled = true
icon_size = 25
item_spacing = 0
main_axis_padding = 10
position = "right"
radius = 10
reserve_space = false
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 20

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 1000.0

[lockscreen_widgets]
enabled = false
schema_version = 2

[notification]
background_opacity = 0.79999998211860657
layer = "overlay"

[osd.kinds]
bluetooth = false
lock_keys = false
media = false
nightlight = false
wifi = false

[shell]
app_icon_color = "on_surface_variant"
app_icon_colorize = true
avatar_path = "/home/zoro/Pictures/.face.png"
corner_radius_scale = 0.40000000596046448
font_family = "Atkinson Hyperlegible Next Medium"
lang = "en"
password_style = "random"
polkit_agent = true

    [shell.animation]
    speed = 1.5000000223517418

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    compact = true
    fetch_exchange_rates = false
    show_icons = false

    [shell.panel]
    open_near_click_control_center = true
    transparency_mode = "glass"

    [shell.screenshot]
    confirm_region = true
    directory = "~/Pictures/Screenshots"

    [shell.session]
    grid = true
    grid_columns = 1

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "3"
        variant = "destructive"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "command"
        command = "'systemctl' 'reboot' '--firmware-setup'"
        countdown_seconds = 10.0
        enabled = true
        glyph = "adjustments"
        label = "Reboot to UEFI"
        shortcut = "5"
        variant = "default"

[theme]
builtin = "Noctalia"
community_palette = "Monochrome"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "m3-monochrome"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "kitty", "mango", "niri", "qt", "starship" ]
    community_ids = [ "spicetify", "obsidian", "zed", "lazygit", "papirus-icons", "telegram", "zathura" ]

[wallpaper]
directory = "/home/zoro/Pictures/Wallpapers"
fill_mode = "stretch"

    [wallpaper.default]
    path = "/home/zoro/Pictures/Wallpapers/wall-16.png"

    [wallpaper.last]
    path = "/home/zoro/Pictures/Wallpapers/wall-16.png"

    [wallpaper.monitors.Virtual-1]
    path = "/home/zoro/Pictures/Wallpapers/wall-16.png"

[weather]
enabled = false

[widget.battery]
hide_when_plugged = true

[widget.date]
format = "{:%d:%m}"

[widget.launcher]
capsule = true
capsule_opacity = 0.5
custom_image = "/home/zoro/Pictures/.nix.png"
custom_image_colorize = true

[widget.spacer_2]
type = "spacer"
